import * as path from "path";
import * as fs from "fs/promises";
import { ExportReader } from "./ExportReader";
import { RojoComparator } from "./RojoComparator";

export class ContextBuilder {
  constructor(
    private readonly reader: ExportReader,
    private readonly rojo: RojoComparator,
  ) {}

  async build(): Promise<string> {
    const info = await this.reader.lastExportInfo();
    const tree = (await this.reader.tree()) ?? [];
    const scripts = (await this.reader.scripts()) ?? [];
    const remotes = (await this.reader.remotes()) ?? [];
    const gui = (await this.reader.gui()) ?? [];
    const rojoDetected = await this.rojo.detect();

    const serverScripts = scripts.filter((s) => s.className === "Script");
    const clientScripts = scripts.filter((s) => s.className === "LocalScript");
    const moduleScripts = scripts.filter((s) => s.className === "ModuleScript");

    const lines: string[] = [];
    lines.push(`# Claude context for ${info?.placeName ?? "this Roblox game"}`);
    lines.push("");
    lines.push(`_Generated by RoTree extension_  `);
    if (info) {
      lines.push(`Last export: \`${info.exportedAt}\` · kind: \`${info.kind}\` · plugin v${info.pluginVersion}`);
    }
    lines.push("");

    lines.push("## Overview");
    lines.push("");
    if (info) {
      for (const [k, v] of Object.entries(info.stats)) {
        lines.push(`- ${k}: **${v}**`);
      }
    }
    lines.push(`- Rojo project: **${rojoDetected ? "detected" : "not detected"}**`);
    lines.push("");

    lines.push("## Services");
    lines.push("");
    for (const node of tree) {
      lines.push(`- \`${node.name}\``);
    }
    lines.push("");

    lines.push("## Server scripts");
    lines.push("");
    if (serverScripts.length === 0) lines.push("_None._");
    for (const s of serverScripts) lines.push(`- \`${s.fullPath}\` — ${s.lines} lines${s.redacted ? " (redacted)" : ""}`);
    lines.push("");

    lines.push("## Client scripts");
    lines.push("");
    if (clientScripts.length === 0) lines.push("_None._");
    for (const s of clientScripts) lines.push(`- \`${s.fullPath}\` — ${s.lines} lines${s.redacted ? " (redacted)" : ""}`);
    lines.push("");

    lines.push("## ModuleScripts");
    lines.push("");
    if (moduleScripts.length === 0) lines.push("_None._");
    for (const s of moduleScripts) lines.push(`- \`${s.fullPath}\` — ${s.lines} lines`);
    lines.push("");

    lines.push("## Remotes");
    lines.push("");
    if (remotes.length === 0) lines.push("_None._");
    for (const r of remotes) lines.push(`- \`${r.fullPath}\` — ${r.className}`);
    lines.push("");

    lines.push("## ScreenGuis");
    lines.push("");
    const screens = gui.filter((g) => g.className === "ScreenGui");
    if (screens.length === 0) lines.push("_None._");
    for (const g of screens) lines.push(`- \`${g.fullPath}\``);
    lines.push("");

    lines.push("## How to use this with Claude");
    lines.push("");
    lines.push(
      "Read `.rotree/game-tree.json` for structure, `.rotree/scripts-map.json` for source, " +
      "`.rotree/remotes-map.json` for the remote surface. Do NOT modify the live game. " +
      "If you want to change something, write a patch into `.rotree/patches/<name>.json` " +
      "and ask the user to apply it via the RoTree plugin → Apply Patch button. " +
      "Critical systems (DataStore, leaderstats, MarketplaceService, anti-cheat) require " +
      "double confirmation in the plugin."
    );

    return lines.join("\n");
  }

  async writeContextFile(): Promise<string> {
    const md = await this.build();
    const out = path.join(this.reader.folder, "CLAUDE_CONTEXT.md");
    await fs.writeFile(out, md, "utf8");
    return out;
  }
}
